# --- Required options --- #
title: Stephen Pincher
author: Stephen Pincher

# --- Navigation Bar --- #
navbar-links:
  Home: "https://stephenpincher.com"
  About Me: "aboutme"
  Social:
    - LinkedIn: "https://www.linkedin.com/in/stephenpincher/"
    - Twitter: "https://twitter.com/StephenPincher"
    - Github: "https://github.com/pinchy76"
  Projects:
    - XER Cleaner: "xercleaner"

# --- Logo & Avatar --- #
avatar: "assets/img/StephenPincherPortrait600x600Round.png"
round-avatar: true

# --- Footer Social Links --- #
social-network-links:
  twitter: stephenpincher
  linkedin: stephenpincher

# --- Site Options --- #
rss-description: "This website is a virtual proof that I'm awesome"
share-links-active:
  twitter: true
  linkedin: true
  vk: false

url-pretty: "StephenPincher.com"
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true

# --- Colours --- #
navbar-col: "#324376"
navbar-text-col: "#FCEFF9"
navbar-border-col: "#DDDDDD"
page-col: "#FCEFF9"
text-col: "#606D5D"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#324376"
footer-text-col: "#606D5D"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# --- Miscellaneous --- #
date_format: "%B %-d, %Y"
timezone: "Europe/London"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# --- Default Layouts --- #
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  - scope:
      path: ""
    values:
      layout: "page"

# --- Plugins --- #
plugins:
  - jekyll-paginate
  - jekyll-sitemap

repository: pinchy76/pinchy76.github.io
github:
  url: "https://github.com/pinchy76/pinchy76.github.io"
baseurl: ""

# --- Exclusions --- #
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CHANGELOG.md
  - CNAME
  - LICENSE
  - README.md
  - screenshot.png
  - docs/